// Mock data for testing the frontend interfaces

// Simplified mock data with just the essential users
export const mockUsers = [
    {
      id: 1,
      username: "admin",
      email: "admin@agileflow.com",
      role: "ADMIN",
      active: true,
    },
    {
      id: 2,
      username: "productowner",
      email: "po@agileflow.com",
      role: "PRODUCT_OWNER",
      active: true,
    },
    {
      id: 3,
      username: "scrummaster",
      email: "sm@agileflow.com",
      role: "SCRUM_MASTER",
      active: true,
    },
    {
      id: 4,
      username: "developer1",
      email: "dev1@agileflow.com",
      role: "DEVELOPER",
      active: true,
    },
    {
      id: 5,
      username: "tester1",
      email: "tester1@agileflow.com",
      role: "TESTER",
      active: true,
    },
  ]
  
  // Mock Projects
  export const mockProjects = [
    {
      id: 1,
      name: "E-Commerce Platform",
      description: "Building a modern e-commerce platform with React frontend and Spring Boot backend",
      status: "ACTIVE",
      startDate: "2023-02-01T00:00:00Z",
      endDate: "2023-06-30T00:00:00Z",
      ownerName: "productowner",
      projectId: 1,
    },
    {
      id: 2,
      name: "Mobile Banking App",
      description: "Developing a secure mobile banking application with biometric authentication",
      status: "ACTIVE",
      startDate: "2023-03-15T00:00:00Z",
      endDate: "2023-08-15T00:00:00Z",
      ownerName: "productowner",
      projectId: 2,
    },
    {
      id: 3,
      name: "Healthcare Management System",
      description: "Creating a comprehensive healthcare management system for hospitals",
      status: "ACTIVE",
      startDate: "2023-01-10T00:00:00Z",
      endDate: "2023-07-10T00:00:00Z",
      ownerName: "productowner",
      projectId: 3,
    },
    {
      id: 4,
      name: "Inventory Management Tool",
      description: "Building an inventory management tool for retail businesses",
      status: "COMPLETED",
      startDate: "2022-10-01T00:00:00Z",
      endDate: "2023-01-15T00:00:00Z",
      ownerName: "productowner",
      projectId: 4,
    },
  ]
  
  // Mock Product Backlogs
  export const mockProductBacklogs = [
    {
      id: 1,
      title: "E-Commerce Platform Backlog",
      description: "Product backlog for the e-commerce platform project",
      projectId: 1,
    },
    {
      id: 2,
      title: "Mobile Banking App Backlog",
      description: "Product backlog for the mobile banking application",
      projectId: 2,
    },
    {
      id: 3,
      title: "Healthcare Management System Backlog",
      description: "Product backlog for the healthcare management system",
      projectId: 3,
    },
    {
      id: 4,
      title: "Inventory Management Tool Backlog",
      description: "Product backlog for the inventory management tool",
      projectId: 4,
    },
  ]
  
  // Mock Sprint Backlogs
  export const mockSprintBacklogs = [
    {
      id: 1,
      title: "E-Commerce Sprint 1 Backlog",
      sprintId: 1,
    },
    {
      id: 2,
      title: "E-Commerce Sprint 2 Backlog",
      sprintId: 2,
    },
    {
      id: 3,
      title: "Mobile Banking Sprint 1 Backlog",
      sprintId: 3,
    },
    {
      id: 4,
      title: "Healthcare Sprint 1 Backlog",
      sprintId: 4,
    },
  ]
  
  // Mock Sprints
  export const mockSprints = [
    {
      id: 1,
      name: "E-Commerce Sprint 1",
      startDate: "2023-02-01T00:00:00Z",
      endDate: "2023-02-15T00:00:00Z",
      sprintBacklogId: 1,
      projectId: 1,
    },
    {
      id: 2,
      name: "E-Commerce Sprint 2",
      startDate: "2023-02-16T00:00:00Z",
      endDate: "2023-03-01T00:00:00Z",
      sprintBacklogId: 2,
      projectId: 1,
    },
    {
      id: 3,
      name: "Mobile Banking Sprint 1",
      startDate: "2023-03-15T00:00:00Z",
      endDate: "2023-03-29T00:00:00Z",
      sprintBacklogId: 3,
      projectId: 2,
    },
    {
      id: 4,
      name: "Healthcare Sprint 1",
      startDate: "2023-01-10T00:00:00Z",
      endDate: "2023-01-24T00:00:00Z",
      sprintBacklogId: 4,
      projectId: 3,
    },
    {
      id: 5,
      name: "E-Commerce Sprint 3",
      startDate: "2023-05-01T00:00:00Z",
      endDate: "2023-05-15T00:00:00Z",
      sprintBacklogId: null,
      projectId: 1,
    },
  ]
  
  // Mock User Stories
  export const mockUserStories = [
    {
      id: 1,
      title: "User Registration",
      description: "As a new customer, I want to register an account so that I can make purchases",
      priority: 1,
      storyPoints: 5,
      acceptanceCriteria:
        "1. User can enter email and password\n2. User receives confirmation email\n3. User can log in after registration",
      productBacklogId: 1,
      sprintBacklogId: 1,
    },
    {
      id: 2,
      title: "Product Browsing",
      description: "As a customer, I want to browse products by category so that I can find what I'm looking for",
      priority: 2,
      storyPoints: 3,
      acceptanceCriteria:
        "1. Products are displayed in a grid\n2. Products can be filtered by category\n3. Products can be sorted by price",
      productBacklogId: 1,
      sprintBacklogId: 1,
    },
    {
      id: 3,
      title: "Shopping Cart",
      description: "As a customer, I want to add products to a cart so that I can purchase multiple items at once",
      priority: 3,
      storyPoints: 8,
      acceptanceCriteria:
        "1. Products can be added to cart\n2. Cart displays total price\n3. Items can be removed from cart",
      productBacklogId: 1,
      sprintBacklogId: 2,
    },
    {
      id: 4,
      title: "Account Login",
      description: "As a returning customer, I want to log in to my account to access my information",
      priority: 1,
      storyPoints: 3,
      acceptanceCriteria:
        "1. User can enter email and password\n2. User is redirected to dashboard after login\n3. User can reset password if forgotten",
      productBacklogId: 2,
      sprintBacklogId: 3,
    },
    {
      id: 5,
      title: "Patient Registration",
      description: "As a hospital staff, I want to register new patients in the system",
      priority: 1,
      storyPoints: 5,
      acceptanceCriteria:
        "1. Staff can enter patient details\n2. System validates required fields\n3. Patient is assigned a unique ID",
      productBacklogId: 3,
      sprintBacklogId: 4,
    },
  ]
  
  // Mock Tasks
  export const mockTasks = [
    {
      id: 1,
      title: "Design registration form",
      description: "Create UI design for the user registration form",
      status: "DONE",
      dueDate: "2023-02-05T00:00:00Z",
      priority: 1,
      estimatedHours: 4,
      loggedHours: 3.5,
      userStoryId: 1,
      assignedUserId: 4,
      assignedUserName: "developer1",
      assignedUserRole: "DEVELOPER",
      sprintId: 1,
      projectId: 1,
      createdAt: "2023-02-01T00:00:00Z",
      updatedAt: "2023-02-05T00:00:00Z",
      comments: [
        {
          id: 1,
          content: "Design completed and approved by the team",
          username: "developer1",
          createdAt: "2023-02-05T00:00:00Z",
        },
      ],
    },
    {
      id: 2,
      title: "Implement registration API",
      description: "Create backend API for user registration",
      status: "DONE",
      dueDate: "2023-02-08T00:00:00Z",
      priority: 1,
      estimatedHours: 6,
      loggedHours: 7,
      userStoryId: 1,
      assignedUserId: 5,
      assignedUserName: "developer2",
      assignedUserRole: "DEVELOPER",
      sprintId: 1,
      projectId: 1,
      createdAt: "2023-02-01T00:00:00Z",
      updatedAt: "2023-02-08T00:00:00Z",
      comments: [
        {
          id: 2,
          content: "API implementation completed",
          username: "developer2",
          createdAt: "2023-02-08T00:00:00Z",
        },
      ],
    },
    {
      id: 3,
      title: "Connect registration form to API",
      description: "Integrate the frontend form with the backend API",
      status: "DONE",
      dueDate: "2023-02-10T00:00:00Z",
      priority: 1,
      estimatedHours: 4,
      loggedHours: 3,
      userStoryId: 1,
      assignedUserId: 4,
      assignedUserName: "developer1",
      assignedUserRole: "DEVELOPER",
      sprintId: 1,
      projectId: 1,
      createdAt: "2023-02-08T00:00:00Z",
      updatedAt: "2023-02-10T00:00:00Z",
      comments: [],
    },
    {
      id: 4,
      title: "Test registration functionality",
      description: "Perform testing on the complete registration flow",
      status: "DONE",
      dueDate: "2023-02-12T00:00:00Z",
      priority: 1,
      estimatedHours: 3,
      loggedHours: 4,
      userStoryId: 1,
      assignedUserId: 6,
      assignedUserName: "tester1",
      assignedUserRole: "TESTER",
      sprintId: 1,
      projectId: 1,
      createdAt: "2023-02-10T00:00:00Z",
      updatedAt: "2023-02-12T00:00:00Z",
      comments: [
        {
          id: 3,
          content: "Found an issue with email validation",
          username: "tester1",
          createdAt: "2023-02-11T00:00:00Z",
        },
        {
          id: 4,
          content: "Issue fixed and retested",
          username: "developer1",
          createdAt: "2023-02-12T00:00:00Z",
        },
      ],
    },
    {
      id: 5,
      title: "Design product grid",
      description: "Create UI design for the product browsing grid",
      status: "DONE",
      dueDate: "2023-02-07T00:00:00Z",
      priority: 2,
      estimatedHours: 5,
      loggedHours: 4,
      userStoryId: 2,
      assignedUserId: 4,
      assignedUserName: "developer1",
      assignedUserRole: "DEVELOPER",
      sprintId: 1,
      projectId: 1,
      createdAt: "2023-02-01T00:00:00Z",
      updatedAt: "2023-02-07T00:00:00Z",
      comments: [],
    },
    {
      id: 6,
      title: "Implement product filtering",
      description: "Create functionality to filter products by category",
      status: "IN_PROGRESS",
      dueDate: "2023-02-20T00:00:00Z",
      priority: 2,
      estimatedHours: 8,
      loggedHours: 4,
      userStoryId: 2,
      assignedUserId: 5,
      assignedUserName: "developer2",
      assignedUserRole: "DEVELOPER",
      sprintId: 2,
      projectId: 1,
      createdAt: "2023-02-16T00:00:00Z",
      updatedAt: "2023-02-18T00:00:00Z",
      comments: [
        {
          id: 5,
          content: "Working on the filter component",
          username: "developer2",
          createdAt: "2023-02-18T00:00:00Z",
        },
      ],
    },
    {
      id: 7,
      title: "Design shopping cart UI",
      description: "Create UI design for the shopping cart",
      status: "TODO",
      dueDate: "2023-02-25T00:00:00Z",
      priority: 3,
      estimatedHours: 6,
      loggedHours: 0,
      userStoryId: 3,
      assignedUserId: 4,
      assignedUserName: "developer1",
      assignedUserRole: "DEVELOPER",
      sprintId: 2,
      projectId: 1,
      createdAt: "2023-02-16T00:00:00Z",
      updatedAt: "2023-02-16T00:00:00Z",
      comments: [],
    },
    {
      id: 8,
      title: "Design login screen",
      description: "Create UI design for the login screen",
      status: "IN_PROGRESS",
      dueDate: "2023-03-20T00:00:00Z",
      priority: 1,
      estimatedHours: 4,
      loggedHours: 2,
      userStoryId: 4,
      assignedUserId: 4,
      assignedUserName: "developer1",
      assignedUserRole: "DEVELOPER",
      sprintId: 3,
      projectId: 2,
      createdAt: "2023-03-15T00:00:00Z",
      updatedAt: "2023-03-17T00:00:00Z",
      comments: [],
    },
    {
      id: 9,
      title: "Design patient registration form",
      description: "Create UI design for the patient registration form",
      status: "TESTING",
      dueDate: "2023-01-15T00:00:00Z",
      priority: 1,
      estimatedHours: 5,
      loggedHours: 6,
      userStoryId: 5,
      assignedUserId: 5,
      assignedUserName: "developer2",
      assignedUserRole: "DEVELOPER",
      sprintId: 4,
      projectId: 3,
      createdAt: "2023-01-10T00:00:00Z",
      updatedAt: "2023-01-15T00:00:00Z",
      comments: [],
    },
    {
      id: 10,
      title: "Unassigned task",
      description: "This is a task without an assigned user",
      status: "TODO",
      dueDate: "2023-03-01T00:00:00Z",
      priority: 3,
      estimatedHours: 2,
      loggedHours: 0,
      userStoryId: 2,
      assignedUserId: null,
      assignedUserName: null,
      assignedUserRole: null,
      sprintId: 2,
      projectId: 1,
      createdAt: "2023-02-16T00:00:00Z",
      updatedAt: "2023-02-16T00:00:00Z",
      comments: [],
    },
  ]
  
  // Project statistics
  export const mockProjectStatistics = {
    totalProjects: 4,
    totalBacklogs: 4,
    totalTasks: 10,
    completedTasks: 4,
    totalUsers: 7,
    totalSprints: 5,
  }
  
  